name: make-lint
on: push
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Step 1
        run: |
          pip install poetry
          poytry add --dev wemake-python-stylegyide
          make lint
